services:
  octotech-frontend:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - /datastore/octotech/nginx-logs:/app/nginx-logs
      - /datastore/octotech/app:/usr/share/nginx/html:ro
      - /datastore/octotech/app/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.octotech.rule=Host(`octotech.az`) || Host(`www.octotech.az`) || Host(`agency.octotech.az`)'
      - 'traefik.http.routers.octotech.entrypoints=web'
      - 'traefik.http.services.octotech.loadbalancer.server.port=80'

networks:
  edge:
    external: true
