events {}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  charset utf-8;
  types { application/manifest+json webmanifest; }

  access_log /app/nginx-logs/access.log;
  error_log  /app/nginx-logs/error.log;

  server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
