services:
  octotech-web:
    build:
      context: .
    restart: unless-stopped
    networks:
      - edge
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      HUBMSG_URL: "https://hubmsgpanel.octotech.az/api/message"
      HUBMSG_API_KEY: ""
      HUBMSG_RECIPIENTS: ""
      HUBMSG_LABEL: "OctotechPortfolio"
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.octotech.rule=Host(`octotech.az`) || Host(`www.octotech.az`) || Host(`agency.octotech.az`)'
      - 'traefik.http.routers.octotech.entrypoints=web'
      - 'traefik.http.services.octotech.loadbalancer.server.port=3000'

networks:
  edge:
    external: true
